### ISSUE TITLE
Status Message Not Showing items correctly

### ISSUE THREAD

**Issue by vnathoo** [IOT-DSA/dslink-java-haystack#11]
The "status" attribute on a connector shows all the errors, rather than the actual connector status (Connected, Connecting etc). I would say that any error associated with a bad query should be added to a different attribute rather than status. The current configuration is causing issues on our end.

**Comment by ilyatsarev** [comment]
@vnathoo could you provide steps to reproduce this issue and confirm you're using the latest dslink version?

**Comment by vnathoo** [comment]
@ilyatsarev Invoking an incorrect eval call, will provide the following.
eval expr: read(idx).fin()
path: /downstream/haystack/test1/Status
value: Unable to connect to https://XX.com/api/YY : axon::EvalErr: Unknown symbol 'fin' [eval:1] : 

The status should not show that it is unable to connect. the connection is up, just the the query return a bad result. That should not be in the status. 

I can confirm that I'm using the latest build.

**Comment by ilyatsarev** [comment]
Hi @vnathoo, and thank you. We've opened an internal ticket to look into that.

**Comment by vnathoo** [comment]
Hi @ilyatsarev do you have a timeline on this?

**Comment by ilyatsarev** [comment]
Hi @vnathoo, not at this moment.
