### ISSUE TITLE
Data Return

### ISSUE THREAD

**Issue by vnathoo** [IOT-DSA/dslink-java-haystack#3]
If an invalid query to Skyfoundry is made, the data that is returned is the last valid query. This only occurs in the second instance. For example, if a successful query was made followed by an unsuccessful query, the data for the unsuccessful query would be the one of the previous query. Ideally the result of the unsuccessful query should be blank.

**Comment by samrg472** [comment]
I don't cache the queries. The only way to do this is to compare the query results which will waste resources.

**Comment by dglogik** [comment]
I believe the request is to have the action return a blank table if an error occurs
